name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Semantic Release
        id: semantic-release
        uses: ./.github/actions/semantic-release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MINOR_RELEASE_WITH_LMS: true
          RALLY_API_KEY: ${{ secrets.RALLY_API_KEY }}
      - name: Test Output
        run: |
          echo version: ${{ steps.semantic-release.outputs.VERSION }} 
