name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Semantic Release
        id: semantic-release
        uses: ./.github/actions/semantic-release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Output
        run: |
          echo release: ${{ steps.semantic-release.outputs.RELEASE }}
          echo version: ${{ steps.semantic-release.outputs.VERSION }} 
